titanic:
  target: titanic_dev
  outputs:
    titanic_dev:
      type: snowflake
      account: fka50167
      warehouse: transforming
      database: analytics
      user: dbtlabs_miguel_dichoso
      password: 11DBTsdm@V1194
      role: transformer
      schema: aaa_titanic_demo
      threads: 10
